
version: "2"

services:
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    user: root
    volumes:
      - "NEXUS-DATA:/nexus-data"
      - ./neuxs/start.sh:/usr/local/bin
    environment:
      - SANS_DNS=ip-172-31-12-159.ap-northeast-2.compute.internal
    entrypoint: start.sh
    networks:
      net:
        ipv4_address: 192.168.102.10

volumes:
  NEXUS-DATA:

networks:
  net:
    driver: host